<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="/app/tests/Station18" tests="4" assertions="4" errors="0" warnings="0" failures="1" skipped="0" time="21.791601">
    <testsuite name="Tests\Station18\Question\QuestionTest" file="/app/tests/Station18/Question/QuestionTest.php" tests="4" assertions="4" errors="0" warnings="0" failures="1" skipped="0" time="21.791601">
      <testcase name="getArray関数内の配列の宣言がshortである" class="Tests\Station18\Question\QuestionTest" classname="Tests.Station18.Question.QuestionTest" file="/app/tests/Station18/Question/QuestionTest.php" line="21" assertions="1" time="2.090537"/>
      <testcase name="関数の順序が正しくならんでいる" class="Tests\Station18\Question\QuestionTest" classname="Tests.Station18.Question.QuestionTest" file="/app/tests/Station18/Question/QuestionTest.php" line="31" assertions="1" time="0.064153"/>
      <testcase name="elseが使用されていないこと" class="Tests\Station18\Question\QuestionTest" classname="Tests.Station18.Question.QuestionTest" file="/app/tests/Station18/Question/QuestionTest.php" line="45" assertions="1" time="0.053962"/>
      <testcase name="php_cs_fixerの結果確認" class="Tests\Station18\Question\QuestionTest" classname="Tests.Station18.Question.QuestionTest" file="/app/tests/Station18/Question/QuestionTest.php" line="55" assertions="1" time="19.582948">
        <failure type="PHPUnit\Framework\ExpectationFailedException">Tests\Station18\Question\QuestionTest::php_cs_fixerの結果確認
Failed asserting that false is true.

/app/tests/Station18/Question/QuestionTest.php:60</failure>
        <system-out>array(3) {
  [0]=&gt;
  string(46) "   1) /app/src/Station18/Question/Question.php"
  [1]=&gt;
  string(0) ""
  [2]=&gt;
  string(76) "Found 1 of 1 files that can be fixed in 0.599 seconds, 14.000 MB memory used"
}
</system-out>
      </testcase>
    </testsuite>
  </testsuite>
</testsuites>
